apiVersion: environment.tf.operator.com/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/instance: workspace-sample
    app.kubernetes.io/part-of: workspace-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: workspace-operator
  name: workspace-sample
spec:
  # TODO(user): Add fields here
